"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { api, ApiError, setToken } from "../../lib/api";
import { Button, ErrorBox } from "../../components/ui";

export default function LoginPage(){
  const router=useRouter(); const [register,setRegister]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const [form,setForm]=useState({email:"",password:"",full_name:"",organization_name:""});
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const result=register?await api.register(form):await api.login({email:form.email,password:form.password});setToken(result.access_token);router.push("/sessions")}catch(error){setError(error instanceof ApiError?error.message:(error as Error).message)}finally{setBusy(false)}}
  return <main className="mx-auto flex min-h-[calc(100vh-150px)] max-w-md items-center px-6 py-12"><section className="panel w-full p-6"><div className="eyebrow">Team access</div><h1 className="mt-2 text-3xl font-bold">{register?"Create your team":"Sign in to PitSense"}</h1><p className="mt-2 text-sm leading-6 text-slate-400">Team accounts keep radio, transcripts, and reports isolated between organizations.</p>{error&&<div className="mt-5"><ErrorBox message={error}/></div>}<form onSubmit={submit} className="mt-6 space-y-4">{register&&<><input required placeholder="Your name" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} className="w-full rounded-lg border border-line bg-ink px-3 py-3 outline-none focus:border-cyan"/><input required placeholder="Team name" value={form.organization_name} onChange={e=>setForm({...form,organization_name:e.target.value})} className="w-full rounded-lg border border-line bg-ink px-3 py-3 outline-none focus:border-cyan"/></>}<input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="w-full rounded-lg border border-line bg-ink px-3 py-3 outline-none focus:border-cyan"/><input required minLength={8} type="password" placeholder="Password (8+ characters)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className="w-full rounded-lg border border-line bg-ink px-3 py-3 outline-none focus:border-cyan"/><Button className="w-full" disabled={busy}>{busy?(register?"Creating…":"Signing in…"):(register?"Create team account":"Sign in")}</Button></form><button onClick={()=>{setRegister(!register);setError("")}} className="mt-5 w-full text-sm text-cyan hover:underline">{register?"Already have an account? Sign in":"Need an account? Create a team"}</button><Link href="/" className="mt-4 block text-center text-xs text-slate-500 hover:text-slate-300">Back to landing page</Link></section></main>
}
