import { AudioLines, BrainCircuit, Database, GitCompareArrows, LockKeyhole, type LucideIcon } from "lucide-react";

const cards: { icon: LucideIcon; title: string; copy: string }[] = [
  { icon: AudioLines, title: "Multilingual speech-to-text", copy: "Multilingual Whisper runs in the FastAPI backend, detects the spoken language automatically, and returns a complete transcript plus timestamped chunks where the model provides them." },
  { icon: BrainCircuit, title: "Audio emotion", copy: "A Hugging Face audio-classification model is the primary, language-independent tone signal. The clip is evaluated in overlapping windows." },
  { icon: GitCompareArrows, title: "Fusion and correlation", copy: "Audio scores are normalized to six application labels. Optional text emotion, urgency keywords, and confidence adjust the event score; high-stress windows are mapped to the active lap and its successor." },
  { icon: Database, title: "Deterministic report", copy: "Rules compare affected laps with the session median, flag deterioration, and produce recommendations. They show association, not causation." },
  { icon: LockKeyhole, title: "Privacy", copy: "Audio stays in the backend storage directory. No external LLM is used. Delete a session to remove its audio and related database records." },
];

export default function Methodology(){return <main className="mx-auto max-w-5xl px-6 py-12"><div className="eyebrow">System notes / methodology</div><h1 className="mt-2 text-4xl font-bold tracking-tight">Transparent by design.</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-400">PitSense AI keeps the signal chain inspectable: model output is stored with raw labels and confidence, and the final engineering action comes from documented deterministic rules.</p><div className="mt-10 grid gap-4 md:grid-cols-2">{cards.map(({icon: Icon,title,copy})=><div className="panel p-5" key={title}><Icon className="text-cyan" size={22}/><h2 className="mt-5 text-lg font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{copy}</p></div>)}</div><div className="panel mt-5 p-6"><div className="eyebrow">Application labels</div><div className="mt-4 flex flex-wrap gap-2">{["calm","stressed","tired","frustrated","urgent","uncertain"].map(label=><span className="rounded-full border border-line px-3 py-2 text-sm capitalize" key={label}>{label}</span>)}</div><p className="mt-5 text-sm leading-6 text-slate-400">Raw model labels such as neutral, fear, anger, sadness, or surprise are retained for transparency and mapped to the application vocabulary. Low confidence results surface “Manual review recommended.”</p></div></main>}
