"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Plus, Trash2 } from "lucide-react";
import { api, ApiError, Session } from "../../lib/api";
import { Badge, Button, ErrorBox, StatusIcon } from "../../components/ui";

export default function SessionsPage() { const router=useRouter(); const [sessions,setSessions]=useState<Session[]>([]); const [error,setError]=useState(""); const [show,setShow]=useState(false); const [busy,setBusy]=useState(false); const [form,setForm]=useState({name:"",driver_name:"",circuit_name:""});
  const load=()=>api.sessions().then(found=>{setSessions(found);if(typeof window!=="undefined"&&new URLSearchParams(window.location.search).get("demo")==="1"){const demo=found.find(item=>item.is_demo);if(demo)window.location.href=`/sessions/${demo.id}`}}).catch(e=>{if(e instanceof ApiError&&e.code==="UNAUTHENTICATED"){router.push("/login");return}setError(e.message)}); useEffect(()=>{load()},[router]);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await api.create(form);setForm({name:"",driver_name:"",circuit_name:""});setShow(false);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function remove(id:number){if(!confirm("Delete this session and its uploaded audio?"))return;try{await api.remove(id);await load()}catch(e){setError((e as Error).message)}}
  return <main className="mx-auto min-h-[calc(100vh-150px)] max-w-7xl px-6 py-12"><div className="flex flex-wrap items-end justify-between gap-5"><div><div className="eyebrow">Operations / sessions</div><h1 className="mt-2 text-4xl font-bold tracking-tight">Analysis sessions</h1><p className="mt-2 text-slate-400">Open a run, add radio and lap timing, then send it through the inference pipeline.</p></div><Button onClick={()=>setShow(!show)}><Plus size={16} className="mr-1 inline"/>New session</Button></div>{error&&<div className="mt-6"><ErrorBox message={error}/></div>}{show&&<form onSubmit={submit} className="panel mt-7 grid gap-4 p-5 md:grid-cols-3"><input required placeholder="Session name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="rounded-lg border border-line bg-ink px-3 py-3 text-sm outline-none focus:border-cyan"/><input required placeholder="Driver name" value={form.driver_name} onChange={e=>setForm({...form,driver_name:e.target.value})} className="rounded-lg border border-line bg-ink px-3 py-3 text-sm outline-none focus:border-cyan"/><input required placeholder="Circuit name" value={form.circuit_name} onChange={e=>setForm({...form,circuit_name:e.target.value})} className="rounded-lg border border-line bg-ink px-3 py-3 text-sm outline-none focus:border-cyan"/><div className="md:col-span-3"><Button disabled={busy}>{busy?"Creating…":"Create session"}</Button></div></form>}<div className="mt-8 grid gap-4">{sessions.length===0&&!error?<div className="panel p-10 text-center text-slate-400">No sessions yet. Create one or open the demo from the landing page.</div>:sessions.map(session=><div className="panel flex flex-wrap items-center gap-4 p-5" key={session.id}><StatusIcon status={session.status}/><div className="min-w-[220px] flex-1"><div className="flex items-center gap-3"><h2 className="font-semibold">{session.name}</h2>{session.is_demo&&<Badge tone="cyan">demo fixture</Badge>}</div><div className="mt-1 text-sm text-slate-400">{session.driver_name} · {session.circuit_name}</div></div><div className="text-xs text-slate-500">{session.audio_count} audio · {session.lap_count} laps</div><Badge tone={session.status==="analysed"?"green":"slate"}>{session.status}</Badge><Link href={`/sessions/${session.id}`} className="rounded-lg border border-line px-3 py-2 text-sm hover:border-cyan">Open</Link><button aria-label={`Delete ${session.name}`} onClick={()=>remove(session.id)} className="rounded-lg p-2 text-slate-500 hover:bg-red-950 hover:text-red-300"><Trash2 size={17}/></button></div>)}</div></main> }
